/**
 * Created by demeter on 2022. 08. 08..
 */

public class GaborClass {
	public static String greetUser(String user) {
		return 'Hello ' + user;
	}
	public static String byeUser(String user) {
		return 'Bye ' + user;
	}
	public static String bye2User(String user) {
		return 'Bye3 ' + user;
	}
	public static String bye3User(String user) {
		for (Integer i = 0; i < 10; i++) {
			insert new Account();
		}
		return null;
	}
}
