name: CI job
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
jobs:
  dev-flow:
    runs-on: ubuntu-latest
    container:
      image: docker://gambe94/sfdx:1.0.0
      credentials:
        username: 'gambe94'
        password: {{secrets.DOCKER_TOKEN}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Creates file "$/files.json", among others
      - name: Create scratch Org
        run: |
          sfdx force:auth:jwt:grant --clientid $PROD_CONSUMERKEY --jwtkeyfile .certificate/server.key --username $PROD_USERNAME --setdefaultdevhubusername -a HubOrg
        env:
          PROD_CONSUMERKEY: {{secrets.PROD_CONSUMERKEY}}
          PROD_USERNAME: {{secrets.PROD_USERNAME}}


