name: CI job
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
jobs:
  dev-flow:
    runs-on: ubuntu-latest
    container:
      image: docker://gambe94/sfdx:2.0.0
      credentials:
        username: "gambe94"
        password: ${{ secrets.DOCKER_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - uses: actions/download-artifact@v3
      #   with:
      #     name: scratch-cred
      # - name: Debug creds
      #   run: |
      #     ls -la
      #     cat creds.json

      - name: Create scratch Org
        run: |
          whoami
          sfdx --version
          sfdx plugins
               # sfdx force:auth:jwt:grant --clientid $PROD_CONSUMERKEY \
               #     --jwtkeyfile ./certificate/server.key \
               #     --username $PROD_USERNAME \
               #     --setdefaultdevhubusername \
               #     --setalias=$PROD_ALIAS

               # sfdx force:org:create --setdefaultusername --definitionfile=config/project-scratch-def.json \
               #   --durationdays=2  --setalias=GaborSC

               # sfdx force:user:password:generate --targetusername GaborSC

               # sfdx force:org:display --targetusername GaborSC --verbose --json | \
               #   jq '{username: .result.username, password: .result.password, instanceUrl: .result.instanceUrl}' > cred.json

               # sfdx force:source:push -f

          sfdx force:auth:jwt:grant --clientid $PROD_CONSUMERKEY \
          --jwtkeyfile ./certificate/server.key \
          --username test-wreywwy0nmvn@example.com \
          --instanceurl=https://power-page-8078-dev-ed.my.salesforce.com \
          --setdefaultdevhubusername \
          --setalias=GaborSC

           sfdx force:org:display --targetusername GaborSC --verbose --json | \
                 jq '{username: .result.username, password: .result.password, instanceUrl: .result.instanceUrl}' > cred.json
          
          sfdx force:source:push -f

        env:
          PROD_CONSUMERKEY: ${{ secrets.PROD_CONSUMERKEY }}
          PROD_USERNAME: ${{ secrets.PROD_USERNAME }}
          PROD_ALIAS: "EburyHub"
      - name: Archive credentials
        uses: actions/upload-artifact@v3
        with:
          name: scratch-cred
          path: cred.json
      - name: Run tests
        run: |
          sfdx force:apex:test:run --codecoverage --outputdir=testResult \
            --testlevel=RunLocalTests \
            --resultformat=human \
            --detailedcoverage \
            -u GaborSC
      - name: Archive testResult
        uses: actions/upload-artifact@v3
        with:
          name: testResult
          path: testResult/*junit.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'testResult/*junit.xml'
