name: CI job
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
jobs:
  dev-flow:
    runs-on: ubuntu-latest
    container:
      image: docker://gambe94/sfdx:2.0.0
      credentials:
        username: 'gambe94'
        password: ${{ secrets.DOCKER_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Creates file "$/files.json", among others
      - name: Create scratch Org
        run: |
          whoami
          sfdx --version
          sfdx plugins
          sfdx force:auth:jwt:grant --clientid $PROD_CONSUMERKEY \
              --jwtkeyfile ./certificate/server.key \
              --username $PROD_USERNAME \
              --setdefaultdevhubusername \
              --setalias=$PROD_ALIAS
          
          sfdx force:org:create --setdefaultusername --definitionfile=config/project-scratch-def.json \
            --durationdays=2  --setalias=GaborSC
          
          sfdx force:user:password:generate --targetusername GaborSC
          
          sfdx force:org:display --targetusername GaborSC --verbose --json | \
            jq '{username: .result.username, password: .result.password, instanceUrl: .result.instanceUrl}' > creds.json

        env:
          PROD_CONSUMERKEY: ${{ secrets.PROD_CONSUMERKEY }}
          PROD_USERNAME: ${{ secrets.PROD_USERNAME }}
          PROD_ALIAS: 'EburyHub'
      - name: Archive credentials
        uses: actions/upload-artifact@v3
        with:
          name: scratch-cred
          path: cred.json



