name: CI job
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
jobs:
  dev-flow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Creates file "$/files.json", among others
      - name: Gather files changed
        uses: trilom/file-changes-action@a6ca26c14274c33b15e6499323aac178af06ad4b
        with:
          fileOutput: 'json'

        # For verification
      - name: Show files changed
        run: cat $HOME/files.json
