name: CI job
on:
  workflow_dispatch:
  push:
    branches:
      - feature/**
      - main
#  pull_request:
jobs:

  init:
    runs-on: ubuntu-latest
    steps:
      - name: Cache scratchOrg cred
        id: cache_scratchOrg_cred
        uses: actions/cache@v3
        with:
          path: |
            cred.json
          key: ${{ github.ref }}


  create_scratch_org:
    needs:
      - init
    if: needs.init.steps.cache_scratchOrg_cred.outputs.cache-hit != 'true'
    uses: gambe94/sfdxAction/.github/workflows/createScratchOrg.yml@main
    with:
      sc_name: ${{ github.ref }}
      sc_duration: '2'
    secrets: inherit

  checkOutput:
    runs-on: ubuntu-latest
    if: needs.init.steps.cache_scratchOrg_cred.outputs.cache-hit == 'true'
    needs:
      - init
      - create_scratch_org
    steps:
      - name: Archive credentials
        uses: actions/download-artifact@v3
        with:
          name: scratch-cred
          path: cred.json

      - name: Validate artifact
        run: cat cred.json

      - name: Validate Job Output
        run: |
          echo ${{ needs.create_scratch_org.outputs.sc_username }}
          echo ${{ needs.create_scratch_org.outputs.sc_password }}
          echo ${{ needs.create_scratch_org.outputs.sc_instanceUrl }}

  dev-flow:
    runs-on: ubuntu-latest
    if: needs.init.steps.cache_scratchOrg_cred.outputs.cache-hit == 'true'
    needs:
      - init
      - create_scratch_org
    container:
      image: docker://gambe94/sfdx:2.0.1
      credentials:
        username: "gambe94"
        password: ${{ secrets.DOCKER_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit == 'false' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Install dependencies
        run: npm install

      - name: Archive credentials
        uses: actions/download-artifact@v3
        with:
          name: scratch-cred
          path: cred.json

      - name: Login scratch Org
        run: |
          cat cred.json 
          echo ${{ needs.create_scratch_org.outputs.sc_username }}
          echo ${{ needs.create_scratch_org.outputs.sc_password }}
          echo ${{ needs.create_scratch_org.outputs.sc_instanceUrl }}
        

        env:
          PROD_CONSUMERKEY: ${{ secrets.PROD_CONSUMERKEY }}
          PROD_USERNAME: ${{ secrets.PROD_USERNAME }}
          PROD_ALIAS: "EburyHub"


      - name: Archive credentials
        uses: actions/upload-artifact@v3
        with:
          name: scratch-cred
          path: cred.json

      - name: Generate dif
        run: |
          
          echo "diff"

      - name: Run tests
        run: |
          sfdx plugins
