name: CI job
on:
  pull_request:

env:
  PROD_CONSUMERKEY: ${{ secrets.PROD_CONSUMERKEY }}
  PROD_USERNAME: ${{ secrets.PROD_USERNAME }}
  PROD_ALIAS: "EburyHub"
  SC_ORG_ALIAS: "GABOR_SC"

jobs:
  create_scratch_org:
    uses: gambe94/sfdxAction/.github/workflows/createScratchOrg.yml@feature/A
    with:
      sc_name: ${SC_ORG_ALIAS}
      sc_duration: '2'
      cred_key: ${{ github.workspace }}-${{ github.ref }}
    secrets: inherit


  dev-flow:
    runs-on: ubuntu-latest
    needs:
      - create_scratch_org
    container:
      image: docker://gambe94/sfdx:2.0.2
      credentials:
        username: "gambe94"
        password: ${{ secrets.DOCKER_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Pull creds
        uses: actions/download-artifact@v3
        with:
          name: scratch-cred

      - name: Encode private key
        run: openssl enc -nosalt -aes-256-cbc -d -in certificate/server.key.enc -out certificate/server.key -base64 -K ${{ secrets.JWT_KEY }} -iv ${{ secrets.JWT_IV }}

      - name: Login scratch Org
        run: |
          echo ${{ needs.create_scratch_org.outputs.sc_username }}
          echo ${{ needs.create_scratch_org.outputs.sc_password }}
          echo ${{ needs.create_scratch_org.outputs.sc_instanceUrl }}
          
          
          sfdx force:auth:jwt:grant --clientid $PROD_CONSUMERKEY \
            --jwtkeyfile certificate/server.key \
            --username $(cat cred.json | jq -r '.username') \
            --instanceurl $(cat cred.json | jq -r '.instanceUrl') \
            --setdefaultusername \
            --setalias $SC_ORG_ALIAS
          
            echo "Login to $SC_ORG_ALIAS"

      - name: Upload salesforce metadata
        run: sfdx force:source:push -u $SC_ORG_ALIAS
        continue-on-error: true


      - name: Generate diff
        run: |
          git branch -r
          git merge-base origin/main  HEAD
          # sfdx sfpowerkit:project:diff --revisionfrom "${MERGE_BASE}" --revisionto HEAD --output ${GENERATED_DIFF_FOLDER} --generatedestructive
          ls -laR ${GENERATED_DIFF_FOLDER}
          java --version
        env:
          GENERATED_DIFF_FOLDER: 'generatedDiff'
        continue-on-error: true

      - name: Run tests
        run: |
          sfdx force:apex:test:run --codecoverage --outputdir=testResult \
            --testlevel=RunLocalTests \
            --resultformat=human \
            --detailedcoverage \
            -u $SC_ORG_ALIAS
      - name: Archive testResult
        uses: actions/upload-artifact@v3
        with:
          name: testResult
          path: |
            testResult/*junit.xml
            testResult/test-result-*-codecoverage.json
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: "testResult/*junit.xml"
