name: Validate PR
on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://gambe94/sfdx:2.0.1
      credentials:
        username: "gambe94"
        password: ${{ secrets.DOCKER_TOKEN }}
    steps:
      - name: Welcome
        run: echo Build
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'


      - uses: sfdx-actions/setup-pmd@v1
      - name: run-pmd
        run: pmd -d ./force-app/main/default/classes -R category/apex/design.xml -f text

  test:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - run: echo "Hello test"


  clean:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    needs:
      - build
      - test

    steps:
      - run: echo "clean"
